### ISSUE TITLE
Python 3 support broken

### ISSUE THREAD

**Issue by giampaolo** [mattgwwalker/msg-extractor#24]
A recent commit broke Python 3 support.
https://github.com/mattgwwalker/msg-extractor/commit/00c438ea07299a9e5b29f9de9225e257dfcfb00a#commitcomment-26740979

**Comment by ese942** [comment]
Can you be more specific?  An error message would help.  I don't use python3, not sure where the problem is.

**Comment by giampaolo** [comment]
The problem is the `print` statement without parentheses (but there may be other runtime issues).
This lib should really use Travis for CI testing on both Python 2 and 3 in order to prevent problems like this.

**Comment by giampaolo** [comment]
I now realize there are no tests. This is bad. :(

**Comment by ese942** [comment]
Easy enough to fix.  I was actually going to replace all the prints with the logging module for better output control.  Haven't gotten around to it yet.

Travis doesn't appear to be cross platform.  From the Travis page:
"Python builds are not available on the OS X environment."
https://docs.travis-ci.com/user/languages/python/

I use OS X, so no go for me.

**Comment by giampaolo** [comment]
Actually it is possible to run OSX tests on Travis with some effort. I.e. from my psutil project:
Relevant files from a project of mine:
https://github.com/giampaolo/psutil/blob/master/.travis.yml
https://github.com/giampaolo/psutil/tree/master/.ci/travis
OSX aside, I think Linux is more important because it's run on servers. But there really should be some simple unit tests first.

**Comment by mattgwwalker** [comment]
Yes, I agree about the unit testing.  I don't have the time to work on this however.

My apologies that those changes broke so much.  I have reverted them for the time being.

**Comment by TheElementalOfCreation** [comment]
This should be fixed in version 0.14

**Comment by crazyqipython** [comment]
I still get error on version 0.14. I use python3.6 On Mac Book Pro.
<img width="652" alt="has_keyerror" src="https://user-images.githubusercontent.com/16516094/47842508-d41b0000-ddf7-11e8-8e34-472106066c19.png">

**Comment by TheElementalOfCreation** [comment]
> I still get error on version 0.14. I use python3.6 On Mac Book Pro.
> <img alt="has_keyerror" width="652" src="https://user-images.githubusercontent.com/16516094/47842508-d41b0000-ddf7-11e8-8e34-472106066c19.png">

Yep, my bad.  **NOW** it should be fixed properly in 0.15

**Comment by crazyqipython** [comment]
OK, Thank you. Is version 0.15 available?

**Comment by TheElementalOfCreation** [comment]
> OK, Thank you. Is version 0.15 available?

Yes. I released it earlier today

**Comment by crazyqipython** [comment]
Fine, Thank you.

**Comment by TheElementalOfCreation** [comment]
This issue should be resolved. If it is not, please comment and I will reopen it.
